# Generated by Django 3.2 on 2021-07-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('real_name', models.CharField(max_length=256)),
                ('fav_p', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.PositiveIntegerField()),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sons', to='basic_app.bakhood')),
            ],
        ),
    ]
