# Generated by Django 3.2 on 2021-07-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/1'),
        ),
    ]
