# Generated by Django 3.2 on 2021-07-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_alter_photo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
