# Generated by Django 3.2 on 2021-07-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_alter_bakhood_bak_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sons',
            name='son_pic',
            field=models.ImageField(blank=True, upload_to='son_pics'),
        ),
    ]
