# Generated by Django 3.2 on 2021-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_sons_son_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakhood',
            name='bak_pic',
            field=models.ImageField(blank=True, default='static/user.jpg', upload_to='bak_pics'),
        ),
        migrations.AlterField(
            model_name='sons',
            name='son_pic',
            field=models.ImageField(blank=True, default='static/user.jpg', upload_to='son_pics'),
        ),
    ]
